/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FreelanceSection } from "./FreelanceSection";
import { FreelanceSectionCountArgs } from "./FreelanceSectionCountArgs";
import { FreelanceSectionFindManyArgs } from "./FreelanceSectionFindManyArgs";
import { FreelanceSectionFindUniqueArgs } from "./FreelanceSectionFindUniqueArgs";
import { DeleteFreelanceSectionArgs } from "./DeleteFreelanceSectionArgs";
import { FreelanceSectionService } from "../freelanceSection.service";
@graphql.Resolver(() => FreelanceSection)
export class FreelanceSectionResolverBase {
  constructor(protected readonly service: FreelanceSectionService) {}

  async _freelanceSectionsMeta(
    @graphql.Args() args: FreelanceSectionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FreelanceSection])
  async freelanceSections(
    @graphql.Args() args: FreelanceSectionFindManyArgs
  ): Promise<FreelanceSection[]> {
    return this.service.freelanceSections(args);
  }

  @graphql.Query(() => FreelanceSection, { nullable: true })
  async freelanceSection(
    @graphql.Args() args: FreelanceSectionFindUniqueArgs
  ): Promise<FreelanceSection | null> {
    const result = await this.service.freelanceSection(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FreelanceSection)
  async deleteFreelanceSection(
    @graphql.Args() args: DeleteFreelanceSectionArgs
  ): Promise<FreelanceSection | null> {
    try {
      return await this.service.deleteFreelanceSection(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
